#!/usr/bin/env  rvm 1.9.3 do ruby

require 'net/http'
require 'nokogiri'
require 'rss'
require 'open-uri'

google_news_query = 'http://news.google.com/news/feeds?q=apologize&output=rss'
google_news_result_url = ''
wordlist = Array.new

open(google_news_query) do |rss|
  feed = RSS::Parser.parse(rss)
  item = feed.items[0]
    google_news_result_url = item.link
end

doc = Nokogiri::HTML(open(google_news_result_url))

all_words = ""
doc.traverse{ |node|
  if node.text? and not node.text =~/^\s*$/
    all_words << node.text
  end
}
wordlist = all_words.split("\s")
wordlist.reject!(&:empty?)
wordlist.each { |word| word.gsub! /\W/, "" }
wordlist.reject! {|w| w.size != 4}
wordlist.map!(&:downcase)
wordlist.uniq!

random_output = ""
random_data = open("http://www.random.org/integers/?num=4&min=0&max=#{wordlist.length}&col=1&base=10&format=plain&rnd=new") { |data|
  generated_number = data.read
  random_output << generated_number.chomp
}
random_numbers = random_output.split(/\s/).map(&:to_i)
10.times {puts "#{wordlist.delete_at(rand(wordlist.size))}-#{wordlist.delete_at(rand(wordlist.size))}"}
